name = "vexa"
main = "_worker.js"
compatibility_date = "2026-04-16"

[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "28d4bfe00e2412a93dd629f3c1edef35"
preview_id = "451c1c18a54b4cc6b1f40d7"

[env.development]
name = "vexa"
